version: "3.8"

services:
  mariadb:
    image: mariadb:10.11
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      MYSQL_ROOT_PASSWORD: ken172ji
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ken172ji
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  wordpress:
    image: wordpress:6.4-fpm-alpine
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ken172ji
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_CACHE', true);
        define('WP_HOME','https://colorspro.com.br');
        define('WP_SITEURL','https://colorspro.com.br');
        define('WP_REDIS_HOST', 'redis');
        define('WP_REDIS_PORT', 6379);
        define('WP_REDIS_DATABASE', 7);
        define( 'RT_WP_NGINX_HELPER_CACHE_PATH', '/var/run/nginx-cache' );
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - backend
      - network_redis

  nginx:
    image: nginx:1.25-alpine
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first 
    labels:
      - traefik.enable=true
      - traefik.http.routers.wordpress_colorspro.rule=Host(`colorspro.com.br`) || Host(`www.colorspro.com.br`)
      - traefik.http.routers.wordpress_colorspro.tls=true
      - traefik.http.routers.wordpress_colorspro.tls.certresolver=le
      - traefik.http.routers.wordpress_colorspro.entrypoints=websecure
      - traefik.http.routers.wordpress_colorspro.service=wordpress_colorspro
      - traefik.http.services.wordpress_colorspro.loadbalancer.server.port=80
    command: >
            sh -c "mkdir -p /var/cache/nginx &&
             chown -R 101:101 /var/cache/nginx &&
             chmod -R 755 /var/cache/nginx &&
             nginx -g 'daemon off;'"
    volumes:
      - wordpress_data:/var/www/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # - cache:/var/cache/nginx
    networks:
      - backend
      - proxy
    depends_on:
      - wordpress

networks:
  network_redis:
    external: true
  proxy:
    external: true
  backend:
    driver: overlay
    attachable: true

volumes:
#  traefik_certificates:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/mysql_data
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/wordpress_data
  # cache:  # Novo volume gerenciado pelo Docker
  #   driver: local    
  # nginx_cache:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: /data/nginx_cache    